name: Publish Documentation

on:
  push:
    branches:
      - main
      - maatheusgois-dd/feature/integrate-all-the-code
    paths:
      - 'README.md'
      - 'docs/**'
      - '.github/workflows/publish-docs.yaml'

jobs:
  build-and-deploy:
    name: Convert and Deploy Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install -g markdown-it@14.0.0 markdown-it-anchor@8.6.7 markdown-it-table-of-contents@0.6.0
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Create docs directory
        run: mkdir -p _site
      
      - name: Generate HTML from README
        run: |
          cat > _site/index.html << EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>SweetPad Documentation</title>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
            <style>
              body {
                max-width: 900px;
                margin: 0 auto;
                padding: 20px;
              }
              img {
                max-width: 100%;
              }
              pre {
                background-color: #f5f5f5;
                padding: 15px;
                border-radius: 5px;
                overflow-x: auto;
              }
              .header-anchor {
                opacity: 0.2;
                text-decoration: none;
                margin-left: 0.2em;
              }
              .header-anchor:hover {
                opacity: 1;
              }
            </style>
          </head>
          <body>
          EOF
          
          markdown-it --html README.md >> _site/index.html
          
          cat >> _site/index.html << EOF
          </body>
          </html>
          EOF
      
      - name: Copy Images
        run: |
          mkdir -p _site/docs/images _site/docs/dev _site/images
          cp -r docs/images/* _site/docs/images/ 2>/dev/null || true
          cp -r docs/dev/* _site/docs/dev/ 2>/dev/null || true
          cp -r images/* _site/images/ 2>/dev/null || true
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 